### ISSUE TITLE
Test::Compile usage

### ISSUE THREAD

**Issue by ppisar** [matisse/Perl-Metrics-Simple#9]
I observe two deficiencies in t/000_compile.t:

First, you raised Test::Compile minimal version in Build.PL recently, but you forgot to add the version into "use Test::Compile" in the test. If a user downgrades Test::Compile between running Build.PL and t/000_compile.t, the test will be run with wrong Test::Compile. In other words, the minimal versions should be specified in code. Not only in metadata. You can fix it with:

~~~
-use Test::Compile;
+use Test::Compile v1.1.0;
~~~

Second, the test checks countperl script twice:

~~~
$test->all_files_ok();
pl_file_ok('bin/countperl');
~~~

all_files_ok() simply iterates over all Perl scripts files:

~~~
$ perl -e 'use Test::Compile; Test::Compile->new->all_files_ok()'
ok 1 - blib/lib/Perl/Metrics/Simple.pm compiles
ok 2 - blib/lib/Perl/Metrics/Simple/Output.pm compiles
ok 3 - blib/lib/Perl/Metrics/Simple/Analysis.pm compiles
ok 4 - blib/lib/Perl/Metrics/Simple/Output/JSON.pm compiles
ok 5 - blib/lib/Perl/Metrics/Simple/Output/HTML.pm compiles
ok 6 - blib/lib/Perl/Metrics/Simple/Output/PlainText.pm compiles
ok 7 - blib/lib/Perl/Metrics/Simple/Analysis/File.pm compiles
ok 8 - blib/script/countperl compiles
# Tests were run but no plan was declared and done_testing() was not seen.
~~~

So you test the script twice. You can fix it by removing the direct pl_file_ok() call.

**Comment by matisse** [comment]
Thank you, both are good points, and I will fix.

**Comment by matisse** [comment]
I will also add the module versions for other module where Build.PL/Makefile.PL specifies a version, e.g. `use IO::File 1.14;`

**Comment by matisse** [comment]
See: https://github.com/matisse/Perl-Metrics-Simple/pull/10

**Comment by ppisar** [comment]
Nice.
